### ISSUE TITLE
Wasm build: unresolved import `arcs::render`

### ISSUE THREAD

**Issue by marcelbuesing** [Michael-F-Bryan/arcs#4]
`yarn start` currently fails. I assume the module is either missing or no longer exists:

```
error[E0432]: unresolved import `arcs::render`
 --> src/app.rs:6:5
  |
6 |     render::{Renderer, Viewport},
  |     ^^^^^^ could not find `render` in `arcs`

error[E0433]: failed to resolve: could not find `render` in `arcs`
  --> src/app.rs:61:15
   |
61 |         arcs::render::to_drawing_coordinates(
   |               ^^^^^^ could not find `render` in `arcs`
```

**Comment by Michael-F-Bryan** [comment]
Lol, over the last hour I've been rearranging the crate so we have a `window` module with all window-related code (not just rendering). The demo was temporarily broken in 5e83eebc102c59b066ad5bede0d04050f25a9935 so I'm guessing you were just unlucky to see the WebAssembly demo in a broken state.

**Comment by marcelbuesing** [comment]
Ok bad luck I see =). Anyway I think it would be nice if the wasm-demo would also be build as part of the CI.

**Comment by Michael-F-Bryan** [comment]
Yep, my long-term plan is to have it built as part of CI and published to GitHub Pages alongside the API docs so people can play around without needing to download or compile anything locally.
